version: "3.8"

services:
  supplier-web:
    build: .
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://host.docker.internal:3000/api" # On Linux, use http://<host-ip>:3000/api
      NODE_ENV: "production"
