version: "3.8"

services:
  admin-web:
    build: .
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: "production"
      NEXT_PUBLIC_API_BASE_URL: "http://host.docker.internal:3000/api" # On Linux, replace host.docker.internal with your host IP
